// <auto-generated />
using System;
using EventFeedbackSystem.EntityFrameworkCore.Shared;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventFeedbackSystem.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250701222845_Index-And-Uniq-User-Email")]
    partial class IndexAndUniqUserEmail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventFeedbackSystem.Core.Auth.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EventFeedbackSystem.Core.Events.Entities.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DateTime = new DateTime(2025, 6, 30, 22, 28, 44, 811, DateTimeKind.Utc).AddTicks(4452),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            IsDeleted = false,
                            Location = "Tehran",
                            Title = "Event 1"
                        },
                        new
                        {
                            Id = 2L,
                            DateTime = new DateTime(2025, 7, 2, 22, 28, 44, 811, DateTimeKind.Utc).AddTicks(4463),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            IsDeleted = false,
                            Location = "Tehran",
                            Title = "Event 2"
                        },
                        new
                        {
                            Id = 3L,
                            DateTime = new DateTime(2025, 7, 3, 22, 28, 44, 811, DateTimeKind.Utc).AddTicks(4466),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            IsDeleted = false,
                            Location = "Tehran",
                            Title = "Event 3"
                        },
                        new
                        {
                            Id = 4L,
                            DateTime = new DateTime(2025, 7, 4, 22, 28, 44, 811, DateTimeKind.Utc).AddTicks(4467),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            IsDeleted = false,
                            Location = "Tehran",
                            Title = "Event 4"
                        },
                        new
                        {
                            Id = 5L,
                            DateTime = new DateTime(2025, 7, 5, 22, 28, 44, 811, DateTimeKind.Utc).AddTicks(4468),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            IsDeleted = false,
                            Location = "Tehran",
                            Title = "Event 5"
                        });
                });

            modelBuilder.Entity("EventFeedbackSystem.Core.Events.Entities.Feedback", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("EventId", "UserId")
                        .IsUnique();

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("EventFeedbackSystem.Core.Events.Entities.Registeration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId", "EventId")
                        .IsUnique();

                    b.ToTable("Registerations");
                });

            modelBuilder.Entity("EventFeedbackSystem.Core.Events.Entities.Feedback", b =>
                {
                    b.HasOne("EventFeedbackSystem.Core.Events.Entities.Event", "Event")
                        .WithMany("Feedbacks")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventFeedbackSystem.Core.Auth.Entities.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventFeedbackSystem.Core.Events.Entities.Registeration", b =>
                {
                    b.HasOne("EventFeedbackSystem.Core.Events.Entities.Event", "Event")
                        .WithMany("Registerations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventFeedbackSystem.Core.Auth.Entities.User", "User")
                        .WithMany("Registerations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventFeedbackSystem.Core.Auth.Entities.User", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Registerations");
                });

            modelBuilder.Entity("EventFeedbackSystem.Core.Events.Entities.Event", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Registerations");
                });
#pragma warning restore 612, 618
        }
    }
}
