// <auto-generated />
using System;
using EventFeedbackSystem.EntityFrameworkCore.Shared;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventFeedbackSystem.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250630042712_Add-Seed")]
    partial class AddSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventFeedbackSystem.Core.Auth.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EventFeedbackSystem.Core.Events.Entities.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DateTime = new DateTime(2025, 6, 29, 4, 27, 12, 494, DateTimeKind.Utc).AddTicks(9742),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            IsDeleted = false,
                            Location = "Tehran",
                            Title = "Event 1"
                        },
                        new
                        {
                            Id = 2L,
                            DateTime = new DateTime(2025, 7, 1, 4, 27, 12, 494, DateTimeKind.Utc).AddTicks(9750),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            IsDeleted = false,
                            Location = "Tehran",
                            Title = "Event 2"
                        },
                        new
                        {
                            Id = 3L,
                            DateTime = new DateTime(2025, 7, 2, 4, 27, 12, 494, DateTimeKind.Utc).AddTicks(9752),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            IsDeleted = false,
                            Location = "Tehran",
                            Title = "Event 3"
                        },
                        new
                        {
                            Id = 4L,
                            DateTime = new DateTime(2025, 7, 3, 4, 27, 12, 494, DateTimeKind.Utc).AddTicks(9753),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            IsDeleted = false,
                            Location = "Tehran",
                            Title = "Event 4"
                        },
                        new
                        {
                            Id = 5L,
                            DateTime = new DateTime(2025, 7, 4, 4, 27, 12, 494, DateTimeKind.Utc).AddTicks(9754),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            IsDeleted = false,
                            Location = "Tehran",
                            Title = "Event 5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
